name: flutter_playground
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  animations:
  audioplayers:
  cloud_firestore:
  cloud_firestore_odm:
  collection:
  convenient_test:
  cupertino_icons:
  dartx:
  expandable:
  firebase_core:
  firebase_crashlytics:
  fl_chart:
  fluentui_system_icons:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown:
  flutter_riverpod:
  flutter_svg:
  flutter_web_auth:
  flutterfire_ui:
  freezed_annotation:
  gap:
  go_router:
  html:
  intersperse:
  intl:
  json_annotation: ^4.8.1
  json_converter_helper:
  material_segmented_control:
  modal_bottom_sheet:
  modal_progress_hud_nsn:
  quiver:
  riverpod_annotation:
  rxdart:
  shimmer:
  simple_logger:
  sliding_sheet:
  smooth_highlight:
  snapping_sheet:
  state_notifier:
  tsuruo_kit:
    git: https://github.com/HTsuruo/flutter_tsuruo_kit
  url_launcher:
  webview_flutter:

dev_dependencies:
  build_runner:
  cloud_firestore_odm_generator: ^1.0.0-dev.75
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  integration_test:
    sdk: flutter
  json_serializable:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # i18n対応
  # ref. https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
    - assets/fruits/

  fonts:
    - family: Fruits
      fonts:
        - asset: fonts/Fruits.ttf

flutter_gen:
  integrations:
    flutter_svg: true
