name: flutter_playground
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  animations:
  audioplayers:
  cloud_firestore:
  cloud_firestore_odm:
  collection:
  convenient_test:
  cupertino_icons:
  dartx:
  expandable:
  firebase_core:
  firebase_crashlytics:
  fl_chart:
  fluentui_system_icons:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown:
  flutter_riverpod:
  flutter_svg:
  flutter_web_auth:
  flutterfire_ui:
  freezed_annotation:
  gap:
  go_router:
  html:
  intersperse:
  intl:
  json_annotation:
  json_converter_helper:
  material_segmented_control:
  modal_bottom_sheet:
  modal_progress_hud_nsn:
  quiver:
  riverpod_annotation:
  rxdart:
  shimmer:
  simple_logger:
  sliding_sheet:
  smooth_highlight:
  snapping_sheet:
  state_notifier:
  tsuruo_kit:
    git: https://github.com/HTsuruo/flutter_tsuruo_kit
  url_launcher:
  webview_flutter:

  stack_trace: any
  cloud_firestore_web: any
  firebase_core_web: any
  flutter_web_plugins: any
  url_launcher_web: any
  flutter_gen: any
dev_dependencies:
  build_runner:
  cloud_firestore_odm_generator: ^1.0.0-dev.75
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  integration_test:
    sdk: flutter
  json_serializable:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # i18n対応
  # ref. https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
    - assets/fruits/

  fonts:
    - family: Fruits
      fonts:
        - asset: fonts/Fruits.ttf

flutter_gen:
  integrations:
    flutter_svg: true
