name: flutter_playground
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  animations:
  audioplayers:
  cloud_firestore:
  cloud_firestore_odm:
  cloud_firestore_web:
  collection:
  convenient_test:
  cupertino_icons:
  dartx:
  expandable:
  firebase_core:
  firebase_core_web:
  firebase_crashlytics:
  flutter:
    sdk: flutter
  flutter_gen:
  flutter_localizations:
    sdk: flutter
  flutter_markdown:
  flutter_riverpod:
  flutter_svg:
  flutter_web_auth:
  flutterfire_ui:
  fl_chart:
  fluentui_system_icons:
  freezed_annotation:
  gap:
  go_router:
  html:
  intersperse:
  intl:
  json_annotation:
  json_converter_helper:
  material_segmented_control:
  modal_bottom_sheet:
  modal_progress_hud_nsn:
  quiver:
  riverpod_annotation:
  rxdart:
  shimmer:
  simple_logger:
  sliding_sheet:
  smooth_highlight:
  snapping_sheet:
  stack_trace:
  state_notifier:
  tsuruo_kit:
    git: https://github.com/HTsuruo/flutter_tsuruo_kit
  url_launcher:
  url_launcher_web:
  webview_flutter:

dev_dependencies:
  build_runner:
  cloud_firestore_odm_generator: ^1.0.0-dev.75
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  integration_test:
    sdk: flutter
  json_serializable:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  # i18n対応
  # ref. https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/fruits/
  fonts:
    - family: Fruits
      fonts:
        - asset: fonts/Fruits.ttf

flutter_gen:
  integrations:
    flutter_svg: true
